### PR TITLE
added windows gateway detection

### PR DESCRIPTION
**Pull request by 0xdcarns**
To test:
Join a network with a Windows node, ensure the host's DefaultGateway and LocalAddress are set appropriately.

### CODE REVIEW

**Comment by Aceix** [comment]
ci tests are broken

**Review by mattkasun — CHANGES_REQUESTED** [review]
go mod requires updating

**Comment by 0xdcarns** [comment]
> go mod requires updating

yes, yes it does

**Review by theguy951357 — APPROVED** [review]
built windows client off of branch
joined network
default gateway and local address is set right.
pass

**Pull request merged**
