### PR TITLE
tech(GRA-726): set netclient config version in SetVersion function

### PR DESCRIPTION
**Pull request by Aceix**

### CODE REVIEW

**Comment by Aceix** [comment]
Not sure how this will affect logic in `cmd/root.go/checkConfig()` @mattkasun

**Comment by mattkasun** [comment]
as discussed in chat I think a bigger refactor of versioning is needed.

**Review by mattkasun — COMMENTED** [review]
I think a bigger refactor of version handling is required.

**Comment by Aceix** [comment]
@mattkasun I guess this PR can be closed

**Pull request closed without merging**
