### PR TITLE
fix(GRA-924): fix gui crashing after join

### PR DESCRIPTION
**Pull request by Aceix**
Depends on: https://github.com/gravitl/netclient/pull/180 

TESTING STEPS:
1. Open GUI, join a network by various means
2. Check that the GUI does not crash, and peers are loaded correctly

### CODE REVIEW

**Review by theguy951357 — APPROVED** [review]
Gui does not crash after join

**Comment by Aceix** [comment]
Rebase and merge after https://github.com/gravitl/netclient/pull/180

**Comment by Aceix** [comment]
@theguy951357 can you retest?

**Comment by theguy951357** [comment]
I am getting this when I open the gui

Screenshot 2023-02-03 at 8 56 28 AM

**Comment by Aceix** [comment]
@theguy951357 should be fixed now

**Comment by theguy951357** [comment]
it doesn't crash on join, but I am getting this now. 
Screenshot 2023-02-06 at 8 08 41 AM

the gui is stuck on my computer and I cant get rid of it even with netclient uninstall

**Pull request closed without merging**
