### PR TITLE
fix(GRA-1413): fix gui not working on windows

### PR DESCRIPTION
**Pull request by Aceix**
## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [x] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [x] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [x] Netclient & Netmaker are awesome.

### CODE REVIEW

**Review by mattkasun — APPROVED** [review]

**Comment by Aceix** [comment]
NB:
- wails version has been downgraded to v2.2.0. we should install the same version of Wails CLI locally as well. the newer versions keep generating wrong typescript bindings
- tests will be fixed in a later story

**Comment by Aceix** [comment]
image

**Comment by Aceix** [comment]
Ubuntu 22.04

image

**Review by theguy951357 — APPROVED** [review]
pr passes. GUI is functional
crritical list passes

**Pull request merged**
